In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0         True
1    15810944   35            20000          0         True
2    15668575   26            43000          0        False
3    15603246   27            57000          0        False
4    15804002   19            76000          0         True
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1        False
396  15706071   51            23000          1         True
397  15654296   50            20000          1        False
398  15755018   36            33000          0         True
399  15594041   49            36000          1        False

[400 rows x 5 columns]

In [6]:
indep=dataset[['Age', 'EstimatedSalary', 'Gender_Male']]   
dep=dataset[["Purchased"]]

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.tree import DecisionTreeClassifier

In [10]:
#https://scikit-learn.org/1.5/modules/generated/sklearn.linear_model.LogisticRegression.html

In [14]:
from sklearn.model_selection import GridSearchCV

# While entering the parameters, we should check in sklearn--> the parameters varies for regression and classification.

param_grid = {'criterion':['gini','entropy',],'max_features': ['sqrt','log2'],'splitter':['best','random']}



grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted')

# fitting the model for grid search

grid.fit(X_train, y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [15]:
# print best parameter after tuning
#print(grid.best_params_)

re=grid.cv_results_


#print(re)

grid_predictions = grid.predict(X_test)

from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, grid_predictions)

#print classification report

from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [16]:
#https://scikit-learn.org/stable/modules/model_evaluation.html --->Using this we can check the evaluation metrics

In [17]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test, grid_predictions,average='weighted')
print("The f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter{'criterion': 'entropy', 'max_features': 'log2', 'splitter': 'best'}: 0.8707635226734645

In [18]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[80  5]
 [12 37]]

In [19]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.87      0.94      0.90        85
           1       0.88      0.76      0.81        49

    accuracy                           0.87       134
   macro avg       0.88      0.85      0.86       134
weighted avg       0.87      0.87      0.87       134

In [20]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.8481392557022809

In [21]:
table=pd.DataFrame.from_dict(re)

In [22]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009375,0.007654,0.021875,0.007655,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.799620,0.813511,0.775815,0.850543,0.883278,0.824553,0.038061,5
1,0.000000,0.000000,0.018749,0.006249,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.787654,0.822155,0.833323,0.850543,0.808775,0.820490,0.021383,7
2,0.003125,0.006250,0.018750,0.006249,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.770712,0.850809,0.814409,0.826499,0.823140,0.817114,0.026154,8
3,0.006249,0.007654,0.018750,0.006250,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.826263,0.813511,0.831098,0.924528,0.844370,0.847954,0.039541,2
4,0.006250,0.007655,0.015624,0.000002,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.826263,0.832918,0.833323,0.885265,0.791152,0.833784,0.030084,3
5,0.009373,0.007653,0.015626,0.000002,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.849794,0.776214,0.735849,0.851527,0.903610,0.823399,0.059688,6
6,0.003124,0.006249,0.015624,0.000002,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.822092,0.868752,0.832483,0.906166,0.905069,0.866912,0.035198,1
7,0.009375,0.007655,0.012500,0.006250,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.782557,0.828959,0.778067,0.885265,0.850543,0.825078,0.040753,4

In [ ]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

In [ ]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#␣change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))