In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0         True
1    15810944   35            20000          0         True
2    15668575   26            43000          0        False
3    15603246   27            57000          0        False
4    15804002   19            76000          0         True
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1        False
396  15706071   51            23000          1         True
397  15654296   50            20000          1        False
398  15755018   36            33000          0         True
399  15594041   49            36000          1        False

[400 rows x 5 columns]

In [6]:
indep=dataset[['Age', 'EstimatedSalary', 'Gender_Male']]   
dep=dataset[["Purchased"]]

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
#https://scikit-learn.org/1.5/modules/generated/sklearn.linear_model.LogisticRegression.html

In [11]:
from sklearn.model_selection import GridSearchCV

# While entering the parameters, we should check in sklearn--> the parameters varies for regression and classification.

param_grid = {'criterion':['gini','entropy',],'max_features': ['sqrt','log2'],'n_estimators':[10,100]}



grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted')

# fitting the model for grid search

grid.fit(X_train, y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1_weighted', verbose=3)

In [12]:
# print best parameter after tuning
#print(grid.best_params_)

re=grid.cv_results_


#print(re)

grid_predictions = grid.predict(X_test)

from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, grid_predictions)

#print classification report

from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [13]:
#https://scikit-learn.org/stable/modules/model_evaluation.html --->Using this we can check the evaluation metrics

In [14]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test, grid_predictions,average='weighted')
print("The f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter{'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}: 0.9256751954513147

In [15]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[79  6]
 [ 4 45]]

In [16]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.95      0.93      0.94        85
           1       0.88      0.92      0.90        49

    accuracy                           0.93       134
   macro avg       0.92      0.92      0.92       134
weighted avg       0.93      0.93      0.93       134

In [17]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9597839135654262

In [18]:
table=pd.DataFrame.from_dict(re)

In [19]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.046873,0.009882,0.024999,7.654617e-03,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.847141,0.832918,0.851527,0.886792,0.943041,0.872284,0.039572,6
1,0.337490,0.007655,0.040623,7.654325e-03,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.867478,0.888107,0.851527,0.925272,0.943699,0.895217,0.034591,4
2,0.043749,0.006250,0.018750,6.249929e-03,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.804764,0.850809,0.832483,0.924528,0.883278,0.859172,0.041461,7
3,0.337489,0.012500,0.040624,7.654928e-03,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.887346,0.888107,0.851527,0.925272,0.943699,0.899190,0.032237,1
4,0.043749,0.006249,0.015624,6.289914e-07,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.847141,0.850809,0.851527,0.906166,0.924528,0.876034,0.032654,5
5,0.374862,0.022975,0.043113,1.007876e-02,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.867478,0.888107,0.851527,0.944161,0.943699,0.898995,0.038480,2
6,0.039125,0.006988,0.015625,1.173833e-06,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.804764,0.811321,0.832483,0.906166,0.923510,0.855649,0.049494,8
7,0.303114,0.044851,0.028124,1.169231e-02,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",0.867478,0.888107,0.851527,0.944161,0.943699,0.898995,0.038480,2

In [ ]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

In [ ]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#␣change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))